# Generated by Django 3.1.2 on 2021-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeMatch', '0002_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hobby',
            field=models.ManyToManyField(blank=True, null=True, related_name='hobby_group', to='DeMatch.Hobby'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject_group', to='DeMatch.Subject'),
        ),
    ]
