# Generated by Django 3.1.2 on 2021-01-04 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeMatch', '0003_auto_20210103_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='talk_from',
        ),
        migrations.AlterField(
            model_name='group',
            name='hobby',
            field=models.ManyToManyField(blank=True, related_name='hobby_group', to='DeMatch.Hobby'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subject_group', to='DeMatch.Subject'),
        ),
        migrations.CreateModel(
            name='UserTalk',
            fields=[
                ('talk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeMatch.talk')),
                ('talk_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('DeMatch.talk',),
        ),
        migrations.CreateModel(
            name='GroupTalk',
            fields=[
                ('talk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DeMatch.talk')),
                ('talk_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to='DeMatch.group')),
            ],
            bases=('DeMatch.talk',),
        ),
    ]
