# Generated by Django 3.1.2 on 2021-01-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeMatch', '0004_auto_20210104_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptalk',
            name='talk_from',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='talk_to',
        ),
        migrations.RemoveField(
            model_name='usertalk',
            name='talk_from',
        ),
        migrations.AddField(
            model_name='grouptalk',
            name='talk_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to='DeMatch.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_from',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='talk_from', to='DeMatch.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertalk',
            name='talk_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='talk_to', to='DeMatch.user'),
            preserve_default=False,
        ),
    ]
