# Generated by Django 3.1.2 on 2021-01-05 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeMatch', '0005_auto_20210105_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='applying',
            field=models.ManyToManyField(blank=True, related_name='applying_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='inviting',
            field=models.ManyToManyField(blank=True, related_name='inviting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
